---
name: wps

'on':
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # NOTE: probably also GitHub actions like
    # [https://github.com/jitterbit/get-changed-files](https://github.com/jitterbit/get-changed-files)
    # can be used to get the list of changed python files
    - run: |
        echo "_CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} -- '*.py' | tr -s '\n' ' ' )" \
        >> ${GITHUB_ENV}
    # NOTE: I have changed action to branch with `INPUT_OPTIONS` quoting fix
    - uses: skarzi/wemake-python-styleguide@patch-1
      if: ${{ env._CHANGED_FILES }}
      with:
        reporter: 'github-pr-review'
        path: "${{ env._CHANGED_FILES }}"
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
